site_name: Zleed Documentation
site_url: https://docs.zleed.tv

repo_url: https://github.com/ZleedApp/Documentation
repo_name: ZleedApp/Documentation

edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 Zleed

nav:
  - Home: index.md
  - Streaming:
    - streaming/index.md
  - Knowledge Base:
    - knowledge-base/index.md
    - FAQ: knowledge-base/faq.md
  - API:
    - api/index.md

theme:
  name: material
  font:
    text: Outfit
    code: Fira Code
  logo: assets/logo.svg
  favicon: favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.indexes
  icon:
    edit: material/pencil 
    view: material/eye
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ZleedApp
      name: GitHub
    - icon: fontawesome/brands/mastodon 
      link: https://tba
      name: Discord
    - icon: fontawesome/brands/discord 
      link: https://tba
      name: Discord

plugins:
  - search
  - offline
  - social:
      cards_layout_options:
        background_color: '#0F172A'
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css