site_name: Zleed Documentation
site_url: https://docs.zleed.tv
site_description: Zleed is a free and open-source streaming platform.

repo_url: https://github.com/ZleedApp/Documentation
repo_name: ZleedApp/Documentation

edit_uri: edit/main/docs/

copyright: Copyright &copy; 2023 Zleed

nav:
  - Home: index.md
  - Knowledge Base:
    - knowledge-base/index.md
    - FAQ: knowledge-base/faq.md
    - Streaming: knowledge-base/streaming.md
    - Discord Bot:
      - knowledge-base/discord-bot/index.md
      - Commands: knowledge-base/discord-bot/commands.md
  - API:
    - api/index.md
    - Auth:
      - Register: api/auth/register.md
      - Login: api/auth/login.md

theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Outfit
    code: Fira Code
  favicon: favicon.ico
  icon: 
    logo: material/file-document-outline
    repo: material/github
    edit: material/note-edit-outline 
    view: material/note-search-outline
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/track-light-off 
        name: Switch to Dark Mode
    - scheme: slate
      toggle:
        icon: material/track-light
        name: Switch to Light Mode

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ZleedApp
      name: GitHub
    - icon: fontawesome/brands/mastodon 
      link: https://tba
      name: Mastodon
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/gaezTFyTV2
      name: Discord
  consent:
    title: Cookie consent
    description: >- 
      This site uses Matomo to analyze traffic and help us to improve your user experience.
      We process your email address and IP address and cookies are stored on your browser for 13 months. 
      This data is only processed by us and our web hosting platform. 
      Please read our Privacy Policy to learn more. 
    cookies:
      analytics: Matomo
  analytics:
    provider: custom
    property: 9

plugins:
  - search
  - social:
      cards_layout_options:
        color: '#E0E7FF'
        background_color: '#6366F1'
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/consent.js